### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by matheusmota** [datasci4health/harena-logger#11]
### Project design
- [ ]  adsasd

---
#### /message
- [x]  Login / jwt token provision
- [x]  Migrate user creation/register to `/user` instead of `/auth`
- [x] Use lucid auto relationship instead of manual query within the controllers
